### ISSUE TITLE
grpc stream can't recv io.EOF

### ISSUE THREAD

**Issue by CandySunPlus** [micro/go-plugins#183]
In example ( micro/example/stream ), when I change client and server to grpc, server can't recv io.EOF error and got rpc error

```
rpc error: code = 1 desc = context canceled
```

client:
```go
import (
	"fmt"

	"context"

	proto "github.com/micro/examples/stream/server/proto"
	"github.com/micro/go-micro"
	grpcClient "github.com/micro/go-plugins/client/grpc"
)

func main() {
	service := micro.NewService(
		micro.Client(grpcClient.NewClient()),
	)
	service.Init()

	// create client
	cl := proto.NewStreamerService("go.micro.srv.stream", service.Client())

	// bidirectional stream
	bidirectional(cl)

	// server side stream
	serverStream(cl)
}
```

server:
```golang
import (
	"fmt"
	"log"

	"context"

	"github.com/micro/go-micro"
	"github.com/micro/go-micro/server"

	proto "github.com/micro/examples/stream/server/proto"
	grpcServer "github.com/micro/go-plugins/server/grpc"
)

func main() {
	// new service
	service := micro.NewService(
		micro.Server(grpcServer.NewServer(server.Name("go.micro.srv.stream"))),
		// micro.Name("go.micro.srv.stream"),
	)

	// Init command line
	service.Init()

	// Register Handler
	proto.RegisterStreamerHandler(service.Server(), new(Streamer))

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by asim** [comment]
I don't receive this error. I've copied your example and it works.

**Comment by CandySunPlus** [comment]
```
2018/05/18 17:01:22 Got msg 10
2018/05/18 17:01:25 Got msg 0
2018/05/18 17:01:25 Got msg 1
2018/05/18 17:01:25 Got msg 2
2018/05/18 17:01:25 Got msg 3
2018/05/18 17:01:25 Got msg 4
2018/05/18 17:01:25 Got msg 5
2018/05/18 17:01:25 Got msg 6
2018/05/18 17:01:25 Got msg 7
2018/05/18 17:01:25 Got msg 8
2018/05/18 17:01:25 Got msg 9
EOF
2018/05/18 17:01:25 Got msg 10
2018/05/18 17:01:48 Got msg 0
2018/05/18 17:01:48 Got msg 1
2018/05/18 17:01:48 Got msg 2
2018/05/18 17:01:48 Got msg 3
2018/05/18 17:01:48 Got msg 4
2018/05/18 17:01:48 Got msg 5
2018/05/18 17:01:48 Got msg 6
2018/05/18 17:01:48 Got msg 7
2018/05/18 17:01:48 Got msg 8
2018/05/18 17:01:48 Got msg 9
EOF
2018/05/18 17:01:48 Got msg 10
2018/05/18 17:05:01 Got msg 0
2018/05/18 17:05:01 Got msg 1
2018/05/18 17:05:01 Got msg 2
2018/05/18 17:05:01 Got msg 3
2018/05/18 17:05:01 Got msg 4
2018/05/18 17:05:01 Got msg 5
2018/05/18 17:05:01 Got msg 6
2018/05/18 17:05:01 Got msg 7
2018/05/18 17:05:01 Got msg 8
2018/05/18 17:05:01 Got msg 9
rpc error: code = 1 desc = context canceled
2018/05/18 17:05:01 Got msg 10
2018/05/18 17:05:04 Got msg 0
2018/05/18 17:05:04 Got msg 1
2018/05/18 17:05:04 Got msg 2
2018/05/18 17:05:04 Got msg 3
2018/05/18 17:05:04 Got msg 4
2018/05/18 17:05:04 Got msg 5
2018/05/18 17:05:04 Got msg 6
2018/05/18 17:05:04 Got msg 7
2018/05/18 17:05:04 Got msg 8
2018/05/18 17:05:04 Got msg 9
EOF
```
Try more times, it happend in sometime

**Comment by asim** [comment]
Have you modified the code in some way?

**Comment by CandySunPlus** [comment]
I pushed my code here

https://github.com/CandySunPlus/examples/tree/master/stream

**Comment by CandySunPlus** [comment]
I just print server stream recv error out

**Comment by asim** [comment]
I'm still not experiencing this issue. What's the setup? Where are you running this? Are you making any config changes?

**Comment by CandySunPlus** [comment]
steps:

1. run consul and the stream server
2.run client 

the error will print on the server side

**Comment by CandySunPlus** [comment]
and how to implement grpc CloseAndRecv and SendAndClose method

**Comment by CandySunPlus** [comment]
here is my recording

https://asciinema.org/a/BDnU5HFZFieFDRfQYqygEMrz7

**Comment by asim** [comment]
Thanks for that. Did you remove the server side logging? As I only see the EOF and context cancellation messages. It's still unclear why it's happening as I don't have the same issue.

**Comment by CandySunPlus** [comment]
In order to make the output cleaner, I only printed the error on the server side.

**Comment by CandySunPlus** [comment]
Thank you for your reply. In what way can I help you to locate the problem?

**Comment by asim** [comment]
I can't replicate the issue so it's difficult to debug

The only thing I can think of is that it might occur here https://github.com/micro/go-plugins/blob/master/server/grpc/grpc.go#L227L240 where a context timeout is set if it's passed in as a header. Otherwise I can't understand why the context would be cancelled.

**Comment by asim** [comment]
Did you manage to debug this further?

**Comment by CandySunPlus** [comment]
sorry, I have no time to debug this further, so I change to use the default go-micro rpc now
